---
title: "Publications"
type: "inverse"
---

Links to the PDF and the OSF page hosting materials and/or data (when available) are provided below. If the PDF, Materials, or Data are not listed below, please reach out directly (hurstm@uchicago.edu). 

Also, although I try to keep this list updated, additional information can be found on [Google Scholar](https://scholar.google.com/citations?user=cLZiGjcAAAAJ&hl=en&oi=ao)

**2022**

Hurst, M. A., Wong, A., Gordon, R., Alam, A., & Cordes, S. (2022). Children’s gesture use provides insight into proportional reasoning strategies. Journal of Experimental Child Psychology, 214, 105277. https://doi.org/10.1016/j.jecp.2021.105277 [[PDF](manuscripts/Hurstetal_ProportionGestures_2022JECP.pdf)] [[OSF](https://osf.io/43p5g/)]

Braithwaite, D. W., McMullen, J., & Hurst, M. A. (2022). Cross-notation knowledge of fractions and decimals. Journal of Experimental Child Psychology, 213, 105210. https://doi.org/10.1016/j.jecp.2021.105210 [[PDF](manuscripts/Braithwaiteetal_CrossNotation_JECP2022.pdf)]

**2021**

Hurst, M. A., Boyer, T. W., & Cordes, S. (2021). Spontaneous and directed attention to number and proportion. Journal of Experimental Psychology: Learning, Memory, and Cognition. https://doi.org/10.1037/xlm0001084 [[PDF](manuscripts/HurstBoyerCordes_NumProp_2021JEPLMC.pdf)] [[OSF](https://osf.io/56r8z/)]

**2020**

Hurst, M. A., Shaw, A., Chernyak, N., & Levine, S. C. (2020). Giving a larger amount or a larger proportion: Stimulus format impacts children’s social evaluations. Developmental Psychology, 56(12), 2212–2222. https://doi.org/10.1037/dev0001121 [[PDF](mmanuscripts/Hurstetal2020_PropSharing_DevPsych.pdf)] [[OSF](https://osf.io/5g34d/)]

Hurst, M. A., Massaro, M., & Cordes, S. (2020). Fraction magnitude: Mapping between symbolic and spatial representations of proportion. Journal of Numerical Cognition, 6(2), 204–230. https://doi.org/10.5964/jnc.v6i2.285 [[PDF](https://jnc.psychopen.eu/index.php/jnc/article/view/5901)] [[OSF](https://osf.io/eycdk/)]

**2019**

Hurst, M. A., & Cordes, S. (2019). Talking about proportion: Fraction labels impact numerical interference in non‐symbolic proportional reasoning. Developmental Science, e12790. https://doi.org/10.1111/desc.12790 [[PDF](manuscripts/HurstCordes_TalkProp_DevSci2018.pdf)] [[OSF](https://osf.io/z4xhv/)]

Hurst, M. A., Polinsky, N., Haden, C. A., Levine, S. C., & Uttal, D. H. (2019). Leveraging Research on Informal Learning to Inform Policy on Promoting Early STEM. Social Policy Report, 32(3), 1–33. https://doi.org/10.1002/sop2.5 [[PDF](https://srcd.onlinelibrary.wiley.com/doi/full/10.1002/sop2.5)]

**2018**

Hurst, M. A., & Cordes, S. (2018). A systematic investigation of the link between rational number processing and algebra ability. British Journal of Psychology, 109(1), 99–117. https://doi.org/10.1111/bjop.12244 [[PDF](manuscripts/HurstCordes_FDNAlg_BriPsych2017.pdf)]


Hurst, M. A., & Cordes, S. (2018). Attending to relations: Proportional reasoning in 3- to 6-year-old children. Developmental Psychology, 54(3), 428–439. https://doi.org/10.1037/dev0000440 [[PDF](manuscripts/HurstCordes_AttendRelations_DevPsych2018.pdf)] [[OSF](https://osf.io/y2sgd/)]


Hurst, M. A., & Cordes, S. (2018). Children’s understanding of fraction and decimal symbols and the notation-specific relation to pre-algebra ability. Journal of Experimental Child Psychology, 168, 32–48. https://doi.org/10.1016/j.jecp.2017.12.003 [[PDF](manuscripts/HurstCordes_FDNKids_JECP2018.pdf)]

**2017**

Hurst, M. A., Anderson, U., & Cordes, S. (2017). Mapping Among Number Words, Numerals, and Nonsymbolic Quantities in Preschoolers. Journal of Cognition and Development, 18(1), 41–62. https://doi.org/10.1080/15248372.2016.1228653 [[PDF](manuscripts/HurstAndersonCordes_NumMap_2017JCD)]


Hurst, M. A., & Cordes, S. (2017). When being good at math is not enough: How students’ beliefs about the nature of mathematics impact decisions to pursue optional math education. In Understanding Emotions in Mathematical Thinking and Learning (pp. 221–241). Academic Press. 

Hurst, M. A., & Cordes, S. (2017). Working memory strategies during rational number magnitude processing. Journal of Educational Psychology, 109(5), 694–708. https://doi.org/10.1037/edu0000169 [[PDF](manuscripts/HurstCordes_WM_JEdPsych2017)] [[OSF](https://osf.io/3ngq2/)]

**2016**

Hurst, M. A., & Cordes, S. (2016). Rational-number comparison across notation: Fractions, decimals, and whole numbers. Journal of Experimental Psychology: Human Perception and Performance, 42(2), 281–293. https://doi.org/10.1037/xhp0000140 [[PDF](manuscripts/HurstCordes_FDNNum_JEPHPP2016)]

**2014**

Hurst, M. A., Leigh Monahan, K., Heller, E., & Cordes, S. (2014). 123s and ABCs: Developmental shifts in logarithmic-to-linear responding reflect fluency with sequence values. Developmental Science, 17(6), 892–904. https://doi.org/10.1111/desc.12165 










